##############################################
# config.yml of the AreaShop plugin          #
# This plugin has been created by NLThijs48  #
# Check the server minecraft.go-craft.com    #
# and then the Survival server for a demo    #
##############################################

########## GENERAL ##########
## Chatprefix used for all messages in the chat. Also check the 'greeting' lines in the 'flagProfiles' section, 
## these also contain the prefix and you may want to change those to
chatPrefix: '&2[AreaShop]&r '
## The characters used for the prices of regions, will appear before the number, for the euro character use '%euro%'
moneyCharacter: '$'
## The characters used after a currency number, '%euro%' will become the euro character
moneyCharacterAfter: ''
## Enables / disables debug messages in the console, no need to change
debug: false
## The .yml language file that should be used, provided by this plugin: EN, NL
language: EN
## Enable Schematic saving and restoring in general
enableSchematics: true
## Maximum number of blocks to save to or restore from a .schemetic
maximumBlocks: 1000000
## Maximum number of locations the teleport function should check to find a safe spot
maximumTries: 50000
## Enable sending stats to http://mcstats.org/ (Metrics plugin)
sendStats: true
## Use colors when sending messages to console and log files
useColorsInConsole: false
## Post error messages in the console when a command run from the config fails (from the 'runCommands' section for example)
postCommandErrors: true
## Version of the config, do not change!
version: 2.0.0
## The different tags you can write on the sign to trigger the plugin
signTags:
  ## Tag for adding a rent region
  rent: '[rent]'
  ## Tag for adding a buy region
  buy: '[buy]'
  ## Tag for adding a sign to an existing region
  add: '[as]'
## Configure the max total regions, max rent regions and max buy regions with different groups (-1 is unlimited)
## Assign a group to players by giving them the permission 'areashop.limits.<group>'
## Every player already has the group 'default' and ops have the unlimited group
## If a player has multiple groups the highest numbers are used
limitGroups:
  default:
    total: 1
    rents: 1
    buys: 1
  unlimited:
    total: -1
    rents: -1
    buys: -1
## Below are profiles for the signs, you can assign profiles to regions 
## by setting 'general.signProfile' in default.yml, groups or individual regions
signProfiles:
  default:
    ## Below is the format for each sign state, the following tags can be used for signs and commands:
    ## %region%, %player%, %uuid%, %price%, %duration%, %world%, %type%, %until%, %untilshort%
    ## The following sections can be added for performing certain commands when the sign is clicked:
    ## rightClickPlayer, rightClickConsole, shiftRightClickPlayer, shiftRightClickConsole,
    ## leftClickPlayer, leftClickConsole, shiftLeftClickPlayer, shiftLeftClickConsole
    ## Sections with 'Player' at the end will be run by the clicking player and 'Console' ones from the console
    forrent:
      line1: '&2&l[For Rent]'
      line2: '%region%'
      line3: '%duration%'
      line4: '%price%'
      rightClickPlayer:
        - 'as rent %region%'
      leftClickPlayer:
        - 'as info region %region%'
    rented:
      line1: '&4&l[Rented]'
      line2: '%region%'
      line3: '%player%'
      line4: '%untilshort%'
      rightClickPlayer:
        - 'as rent %region%'
      leftClickPlayer:
        - 'as info region %region%'
      shiftRightClickPlayer:
        - 'as unrent %region%'
    forsale:
      line1: '&2&l[For Sale]'
      line2: '%region%'
      line3: '%price%'
      line4:
      rightClickPlayer:
        - 'as buy %region%'
      leftClickPlayer:
        - 'as info region %region%'
    sold:
      line1: '&4&l[Sold]'
      line2: '%region%'
      line3: '%player%'
      line4:
      rightClickPlayer:
        - 'as buy %region%'
      leftClickPlayer:
        - 'as info region %region%'
      shiftRightClickPlayer:
        - 'as sell %region%'
## Option to run certain commands when one of these events happen
## Commands at a 'before' section will execute before the region details are changed in the AreaShop system
## and before any other actions occurred (changing signs, saving/loading schematics, etc.),
## the 'after' commands will be run when all changes are done.
## After 'before' or 'after' you can create a list of commands (see example at the created event)
eventCommandProfiles:
  default:
    created:
      before:
      after:
  ##    - "say An AreaShop region has been created: %region%"
    deleted:
      before:
      after:
    rented:
      before:
      after:
    extended:
      before:
      after:
    unrented:
      before:
      after:
    bought:
      before:
      after:
    sold:
      before:
      after:
## For the following events you can specify if you want to restore or save the region to a schematic
## After 'save:' or 'restore:' you enter the name of the file, %region% will be replaced by the region name (.schematic will be added automatically)
## %type% represents the type of the region, could be 'rent' or 'buy'
## If your regions are all the same size you could use just 1 file as the restore file, just enter a name without %region%
## Be carefull with these options, it could crash your server or destroy (parts of) your world if used wrong!
schematicProfiles:
  default:
    created:
      save: '%type%-%region%'
      restore: ''
    deleted:
      save: ''
      restore: '%type%-%region%'
    rented:
      save: ''
      restore: ''
    unrented:
      save: ''
      restore: '%type%-%region%'
    bought:
      save: ''
      restore: ''
    sold:
      save: ''
      restore: '%type%-%region%'
## Flag profiles to specify what flags should be set on the WorldGuard regions
## All region flags can be used + members, owners, priority and parent.
flagProfiles:
  default:
    forrent:
      members: -%player%
      greeting: '&2[AreaShop]&f %region% can be rented for %price% per %duration%'
    rented:
      members: +%player%
      greeting: '&2[AreaShop]&f %region% is rented by %player% until %until%'
    forsale:
      members: -%player%
      greeting: '&2[AreaShop]&f %region% can be bought for %price%'
    sold:
      members: +%player%
      greeting: '&2[AreaShop]&f %region% is bought by %player%'
      
      
########## RENTING ##########
## How much seconds between checking if renting has expired (don't put this to low)
checkDelay: 60
## Timeformat to use on the signs, default is like '30-06 14:52', US format: 'MM-dd KK:mm a'
## Search for 'java SimpleDateFormat' for more options and documentation
timeFormatSign: 'dd-MM HH:mm'
## Timeformat used in the chat, default is like '30 june 2014 14:52', US format: 'MMMMMMMMMMMMMMMMM dd yyyy KK:mm a'
## Search for 'java SimpleDateFormat' for more options and documentation
timeFormatChat: 'dd MMMMMMMMMMMMMMMMM yyyy HH:mm'
## Time indicators, used for specifing rent duration on the signs
## Be careful with deleting words, will break signs using those, adding is no problem
minutes: [m, min, mins, minute, minutes, minuten, minuut]
hours: [h, hour, hours, uur, uren]
days: [d, day, days, dag, dagen]
months: [M,  month,  months, maanden, maand]
years: [y, year, years, jaar, jaren]


