##############################################
# config.yml of the AreaShop plugin          #
# This plugin has been created by NLThijs48  #
# Check the server minecraft.go-craft.com    #
# and then the Prison server for a demo      #
##############################################

########## GENERAL ##########
## Chatprefix used for all messages in the chat
chatPrefix: '&2[AreaShop]&r '
## The character used for the prices of regions, for the euro character use '%euro%'
moneyCharacter: '$'
## Enables / disables debug messages in the console, no need to change
debug: false
## The .yml language file that should be used, provided by this plugin: EN, NL
language: EN
## Maximum total amount of rents and buys together
maximumTotal: 1
## Enable Schematic saving and restoring in general
enableSchematics: true
## Maximum number of blocks to save to or restore from a .schemetic
maximumBlocks: 1000000

########## RENTING ##########
## The tag you have to write on the sign for renting a region
rentSign: '[rent]'
## The line that should be placed on the sign when the region is not rented
signRentable: '&2&l[For Rent]'
## The line that should be placed on the sign when the region is rented
signRented: '&4&l[Rented]'
## How much regions a player can rent at the same time, -1 for not limited
maximumRents: 1
## The percentage of the renting price you get back if you unrent the region (price of time left will be multiplied by this/100)
rentMoneyBack: 100
## How much seconds between checking if renting has expired (don't put this to low)
checkDelay: 60
## Flags for the 'For Rent' regions, flags and options to apply when the region is not rented
## All region flags can be used + members, owners, priority and parent.
flagsForRent:
  members: -%player%
  greeting: '%region% can be rented for %price% per %duration%'
## Flags for the 'Rented' regions, flags and options to apply when the region is rented
## All region flags can be used + members, owners, priority and parent.
flagsRented:
  members: +%player%
  greeting: '%region% is rented by %player% until %until%'

## Enable or disable saving and restoring for rents that don't have their individual option set
useRentRestore: false
## For the following events you can specify if you want to restore or save the region to a schematic
## After 'save:' or 'restore:' you enter the name of the file, %region% will be replaced by the region name (.schematic will be added automatically)
## If your regions are all the same size you could use just 1 file as the restore file, just enter a name without %region%
## Be carefull with these options, it could crash your server or destroy (parts of) your world if used wrong!
rentSchematicProfiles:
  default:
    created:
      save: 'rent-%region%'
      restore: ''
    deleted:
      save: ''
      restore: 'rent-%region%'
    rented:
      save: ''
      restore: ''
    unrented:
      save: ''
      restore: 'rent-%region%'

########## BUYING ##########
## The tag you have to write on the sign for renting a region
buySign: '[buy]'
## The line that should be placed on the sign when the region is not sold
signBuyable: '&2&l[For Sale]'
## The line that should be placed on the sign when the region is sold
signBuyed: '&4&l[Sold]'
## How much regions a player can buy at the same time, -1 for not limited
maximumBuys: 1
## The percentage of the buying price you get back if you sell the region
buyMoneyBack: 100
## Flags for the 'For Sale' regions, flags and options to apply when the region is for sale
## All region flags can be used + members, owners, priority and parent.
flagsForSale:
  members: -%player%
  greeting: '%region% can be bought for %price%'
## Flags for the 'Sold' regions, flags and options to apply when the region is rented
## All region flags can be used + members, owners, priority and parent.
flagsSold:
  members: +%player%
  greeting: '%region% is bought by %player%'

## Enable or disable saving and restoring for buys that don't have their individual option set
useBuyRestore: false
## For the following events you can specify if you want to restore or save the region to a schematic
## After 'save:' or 'restore:' you enter the name of the file, %region% will be replaced by the region name (.schematic will be added automatically)
## If your regions are all the same size you could use just 1 file as the restore file, just enter a name without %region%
## Be carefull with these options, it could crash your server or destroy (parts of) your world if used wrong!
## ('bought' and 'sold' are from the players perspective)
buySchematicProfiles:
  default:
    created:
      save: 'buy-%region%'
      restore: ''
    deleted:
      save: ''
      restore: 'buy-%region%'
    bought:
      save: ''
      restore: ''
    sold:
      save: ''
      restore: 'buy-%region%'