### All settings below are default settings and can be overridden
### by group settings or region settings (copy a section to a region or group and change them there)

########## GENERAL ##########  
general:
  ## Set this to true to enable saving/restoring for regions as specified in the profile below, which is specified in the config
  enableRestore: false
  ## The schematic profile as specified in the config
  schematicProfile: 'default'
  ## The event commands profile as specified in the config
  eventCommandProfile: 'default'
  ## The profile for the format of the sign as specified in the config
  signProfile: 'default'
  ## The profile for the WorldGuard flags as specified in the config
  flagProfile: 'default'
  ## The y location within the region to start searching for safe teleport spots (x and z will be in the middle of the region)
  ## Possible values: bottom, middle, top
  teleportLocationY: bottom
  ## If true the teleportation algorithm only allows telportation to inside the region, otherwise it will expand algorithm
  ## a cube from the starting point to check for safe spots (then it could end outside the region)
  ## If you set a teleport location outside of the region with /as settp then setting this to true breaks that teleport (players cannot use it)
  teleportIntoRegion: true

########## RENTING ##########
rent:
  ## The default price of a renting region
  price: 1000
  ## The default duration of a renting region
  duration: '1 day'
  ## The percentage of the renting price you get back if you unrent the region (price of time left will be multiplied by this/100)
  moneyBack: 100
  ## Maximum number of extends a player can do (-1 for infinite, 0 for no extending)
  maxExtends: -1

########## BUYING ##########
buy:
  ## The default price of a buying region
  price: 1000
  ## The percentage of the buying price you get back if you sell the region
  moneyBack: 100
